YEAR:
  - 2017
VER:
  - 15
CHOST:
  - x86_64-pc-windows-msvc19.14.26423

MSVC_HEADERS_VERSION:
  - 14.16.27023

WINSDK_VERSION:
  - 10.0.17763.0

# FINAL_* entries are taken from the linux64 entries in
# https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/main/recipe/conda_build_config.yaml;
# Removed -fPIC & -fno-plt
FINAL_CFLAGS:
  - -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe

FINAL_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe
