# match vsyear / vsver / cl_version from
# https://github.com/conda-forge/vc-feedstock/blob/main/recipe/conda_build_config.yaml
VSYEAR:
  - 2017
VSVER:
  - 15
CL_VERSION:
  - 19.16.27033

# toolchain name in Microsoft.VisualStudio.Component.VC.<TC_NAME>.x86.x64, see
# https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools
TC_NAME:
  - v141

# header version corresponding to minor version (i.e. x in VS 15.x), see last digits of _MSC_FULL_VER in
# https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering;
# alternatively, download & inspect the *.vsix binaries (for details see install-pkg.sh)
MSVC_HEADERS_VERSION:
  - 14.16.27023

# use latest version from https://github.com/conda-forge/ucrt-feedstock/blob/main/recipe/meta.yaml
WINSDK_VERSION:
  - 10.0.17763.0
# ensure that the above version matches what's under
# https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
# and extract the link for the iso from there
WINSDK_URL:
  - https://go.microsoft.com/fwlink/p/?LinkID=2033686

CHOST_BASE:
  - x86_64-pc-windows-msvc

# FINAL_* entries are taken from the linux64 entries in
# https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/main/recipe/conda_build_config.yaml;
# Removed -fPIC & -fno-plt
FINAL_CFLAGS:
  - -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe

FINAL_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe
