YEAR:
  - 2017
VER:
  - 15

WINSDK_VERSION:
  - 10.0.17763.0

MSVC_HEADERS_VERSION:
  - 14.14.26423
# We would like to upgrade this but sadly don't find a compatible version currently
#  - 14.16.27012

CHOST:
  - x86_64-pc-windows-msvc19.16.27038

