# match vsyear / vsver / cl_version (for CHOST suffix) from
# https://github.com/conda-forge/vc-feedstock/blob/main/recipe/conda_build_config.yaml
VSYEAR:
  - 2017
VSVER:
  - 15
CHOST:
  - x86_64-pc-windows-msvc19.14.26423

# header version corresponding to minor version (i.e. x in VS 15.x), see last digits of _MSC_FULL_VER in
# https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering;
# alternatively, download & inspect the *.vsix binaries (for details see activate-msvc-headers-libs.sh)
MSVC_HEADERS_VERSION:
  - 14.16.27023

# use latest version from https://github.com/conda-forge/ucrt-feedstock/blob/main/recipe/meta.yaml
WINSDK_VERSION:
  - 10.0.17763.0

# FINAL_* entries are taken from the linux64 entries in
# https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/main/recipe/conda_build_config.yaml;
# Removed -fPIC & -fno-plt
FINAL_CFLAGS:
  - -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe

FINAL_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe
