# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      ? osx_64_CLANG_VERSION15.0.7CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_main
      : CONFIG: osx_64_CLANG_VERSION15.0.7CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_main
        UPLOAD_PACKAGES: 'True'
      ? osx_64_CLANG_VERSION15.0.7CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_main
      : CONFIG: osx_64_CLANG_VERSION15.0.7CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_main
        UPLOAD_PACKAGES: 'True'
      ? osx_64_CLANG_VERSION16.0.6CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_main
      : CONFIG: osx_64_CLANG_VERSION16.0.6CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_main
        UPLOAD_PACKAGES: 'True'
      ? osx_64_CLANG_VERSION16.0.6CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_main
      : CONFIG: osx_64_CLANG_VERSION16.0.6CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_main
        UPLOAD_PACKAGES: 'True'
      ? osx_64_CLANG_VERSION17.0.0.rc1CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_llvm_rc
      : CONFIG: osx_64_CLANG_VERSION17.0.0.rc1CL_VERSION19.29.30139MSVC_HEADERS_VERSION14.29.30133TOOLCHAIN_COMBINED14.29.16.11channel_targetsconda-forge_llvm_rc
        UPLOAD_PACKAGES: 'True'
      ? osx_64_CLANG_VERSION17.0.0.rc1CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_llvm_rc
      : CONFIG: osx_64_CLANG_VERSION17.0.0.rc1CL_VERSION19.36.32532MSVC_HEADERS_VERSION14.36.32532TOOLCHAIN_COMBINED14.36.17.6channel_targetsconda-forge_llvm_rc
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)